export const monthsList = [
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "10",
  "11",
  "12",
];

export const yearsList = [
  "2024",
  "2025",
  "2026",
  "2027",
  "2028",
  "2029",
  "2030",
];

export const INITIAL_BALANCE = 2000;

export const DUMMY_TRANSACTIONS = [
  {
    id: 1,
    date: "2024-12-12",
    description: "Grocery",
    amount: -50,
    type: "Debit",
    name: "Local Grocery Store",
    email: "store@example.com",
  },
  {
    id: 2,
    date: "2024-12-10",
    description: "Online Purchase",
    amount: -150,
    type: "Debit",
    name: "Amazon",
    email: "orders@amazon.com",
  },
  {
    id: 3,
    date: "2024-12-08",
    description: "Salary Credit",
    amount: 2000,
    type: "Credit",
    name: "ABC Corp",
    email: "payroll@abccorp.com",
  },
  {
    id: 4,
    date: "2024-12-05",
    description: "Utility Bill Payment",
    amount: -100,
    type: "Debit",
    name: "City Electricity Board",
    email: "billing@citypower.com",
  },
  {
    id: 5,
    date: "2024-12-02",
    description: "Transfer to Savings",
    amount: -500,
    type: "Debit",
    name: "John Doe (Savings Account)",
    email: "john.savings@example.com",
  },
  {
    id: 6,
    date: "2024-11-30",
    description: "Dinner at Restaurant",
    amount: -75,
    type: "Debit",
    name: "Gourmet Bistro",
    email: "contact@gourmetbistro.com",
  },
  {
    id: 7,
    date: "2024-11-28",
    description: "Gift Received",
    amount: 300,
    type: "Credit",
    name: "Jane Smith",
    email: "jane.smith@example.com",
  },
  {
    id: 8,
    date: "2024-11-25",
    description: "Gym Membership",
    amount: -60,
    type: "Debit",
    name: "Fitness Center",
    email: "info@fitnesscenter.com",
  },
  {
    id: 9,
    date: "2024-11-22",
    description: "Car Fuel",
    amount: -40,
    type: "Debit",
    name: "Fuel Station",
    email: "support@fuelstation.com",
  },
  {
    id: 10,
    date: "2024-11-20",
    description: "Freelance Payment",
    amount: 500,
    type: "Credit",
    name: "XYZ Agency",
    email: "payments@xyzagency.com",
  },
  {
    id: 11,
    date: "2024-11-18",
    description: "Mobile Recharge",
    amount: -20,
    type: "Debit",
    name: "Telecom Operator",
    email: "recharge@telecom.com",
  },
  {
    id: 12,
    date: "2024-11-15",
    description: "Birthday Gift Sent",
    amount: -100,
    type: "Debit",
    name: "Emily Brown",
    email: "emily.brown@example.com",
  },
  {
    id: 13,
    date: "2024-11-12",
    description: "Refund from Vendor",
    amount: 30,
    type: "Credit",
    name: "Retail Vendor",
    email: "refunds@vendor.com",
  },
  {
    id: 14,
    date: "2024-11-10",
    description: "Flight Booking",
    amount: -300,
    type: "Debit",
    name: "Travel Agency",
    email: "booking@travelagency.com",
  },
  {
    id: 15,
    date: "2024-11-08",
    description: "Charity Donation",
    amount: -50,
    type: "Debit",
    name: "Helping Hands",
    email: "donations@helpinghands.org",
  },
  {
    id: 16,
    date: "2024-11-05",
    description: "Cashback Received",
    amount: 10,
    type: "Credit",
    name: "Bank Cashback",
    email: "cashback@bank.com",
  },
  {
    id: 17,
    date: "2024-11-03",
    description: "Book Purchase",
    amount: -25,
    type: "Debit",
    name: "Bookstore",
    email: "sales@bookstore.com",
  },
  {
    id: 18,
    date: "2024-11-01",
    description: "Investment Returns",
    amount: 150,
    type: "Credit",
    name: "Investment Firm",
    email: "returns@investfirm.com",
  },
  {
    id: 19,
    date: "2024-10-30",
    description: "Groceries",
    amount: -45,
    type: "Debit",
    name: "Supermarket",
    email: "contact@supermarket.com",
  },
  {
    id: 20,
    date: "2024-10-28",
    description: "Subscription Renewal",
    amount: -12,
    type: "Debit",
    name: "Streaming Service",
    email: "support@streaming.com",
  },
];
